### ISSUE TITLE
Support USD for Poloniex

### ISSUE THREAD

**Issue by mingrammer** [DingdingKim/CoinNow#1]
How about support the USD option for Poloniex? (Of course, I'm willing to send a PR for this later)

**Comment by DingdingKim** [comment]
OK ! I will add it to the next version! Thank you 👍

**Comment by junhocho** [comment]
+ 1 
좋은앱 감사합니다.
Thx for the app!

**Comment by DingdingKim** [comment]
@junhocho 워우 감사합니다 ! 아무것도 아닌앱인데 써주시는 분들이 계시다니! 뿌듯해유 !! 😄 👍

**Comment by mingrammer** [comment]
It seems was resolved. Thank you.
