### ISSUE TITLE
Dashboard would not be auto closed

### ISSUE THREAD

**Issue by mingrammer** [DingdingKim/CoinNow#2]
The menubar dashboard would not be closed even when click the outside of app

**Comment by DingdingKim** [comment]
That is not bug ㅠ I did it on purpose... ㅠ I also wanted to keep checking it when using other apps.
But mac OS user said that is unnatural(I mainly use Window ㅠ). So I will update this issue !! Thank you !! 😃

**Comment by mingrammer** [comment]
This seems also was resolved. Thank you.
