### ISSUE TITLE
실행이 안됩니다.

### ISSUE THREAD

**Issue by junhocho** [DingdingKim/CoinNow#6]
어제? 오늘? 부터 아예 안켜지네요 ㅠㅠ 새로운 버전 설치했는데도 계속 안켜집니다.
켜지자마자 바로 꺼집니다. 확인부탁드립니다.

**Comment by DingdingKim** [comment]
아 ㅠ 죄송합니다 ㅠ 흑 ㅠㅠㅠ 지금 야후 환율 api에서 값을 제대로 못가져오고 있습니다 ㅠ 그래서 일단 야후에서 값을 못 가져 오는경우 제 개인서버에서 고정 환율을 가져오는 방식으로 업데이트 중입니다 ㅠ 늦어도 모레까지는 업데이트 되도록 하겠습니다 ㅠㅠㅠㅠ 관심가져주셔서 감사합니다 !

**Comment by junhocho** [comment]
아이고 그랬었군요 ㅠㅠ yahoo-api 가 터질때도 있군요. 감사합니다~

**Comment by DingdingKim** [comment]
안녕하세요 ! 코인나우 업데이트 되었습니다 ! 업데이트 해주세요 ~ ^^
