### ISSUE TITLE
SecretApi.swift 파일이 없습니다.

### ISSUE THREAD

**Issue by techinpark2** [DingdingKim/CoinNow#7]
SecretApi.swift 파일이 없습니다.
그래서 컴파일이 안되고 있네요 ~~
부탁드립니다.

**Comment by dhlwing** [comment]
Same, can't find the SecretApi.swift

**Comment by DingdingKim** [comment]
@techinpark  아 ㅠ 죄송합니다 ㅠ SecretApi.swift에 제 개인 서버에서 환율정보가지고오는부분, 알림말 가지고오는 부분이 추가되어있는거라 ignore시켜놨더니 ㅠㅠㅠ 제가 조만간 환율가지고오는 부분을 좀 로직을 바꿀 예정이라 그부분 완성되면 바로 포함해서 올리도록 하겠습니다 ! 

@dhlwing  I'm sorry. I have been ignoring the SecretApi.swift on my personal server, which is part of bringing the exchange rate information and the part to get the message. I am going to change the logic part of the exchange rate sooner or later. I will include it immediately!

**Comment by Gargo** [comment]
voted up to fix this bug)
